CREATE TABLE TAGS(
                     TAG_ID NUMBER(3) PRIMARY KEY,
                     TAG_NAME varchar2 (40) UNIQUE NOT NULL,
                     TAG_TYPE varchar2 (10) NOT NULL
);

CREATE SEQUENCE SEQ_TAGS START WITH 1 INCREMENT BY 1 MAXVALUE 999;

-- Genre (장르) 8개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Action', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Comedy', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Drama', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Thriller', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Horror', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Romance', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Fantasy', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Sci-Fi', 'Genre');

-- Studio (제작사) 7개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Marvel Studios', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Pixar', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Warner Bros.', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Disney', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Paramount', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Universal', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Studio Ghibli', 'Studio');

-- Country (국가) 7개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'USA', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Japan', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'France', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'UK', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'South Korea', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'India', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Germany', 'Country');

-- Mood (분위기) 8개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Dark', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Lighthearted', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Suspenseful', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Romantic', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Inspiring', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Melancholic', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Uplifting', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Violent', 'Mood');

-- ===========================================================================
-- ===========================================================================
-- =========================MOVIE_TAGS TABLE================================
-- ===========================================================================
-- ===========================================================================

CREATE TABLE MOVIE_TAGS (
                            MOVIE_ID NUMBER(3),
                            TAG_ID NUMBER(3) ,
                            PRIMARY KEY (MOVIE_ID, TAG_ID),
                            FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID) ON DELETE CASCADE,
                            FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID) ON DELETE CASCADE
);
-- Inside Out 2 (Movie_ID = 1)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 2);  -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 12); -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 16); -- USA
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 24); -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 27); -- Inspiring

-- Despicable Me 4 (Movie_ID = 2)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 2);  -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 14); -- Universal
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 16); -- USA
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 24); -- Lighthearted

-- 탈주 (Movie_ID = 3)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 3);  -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 20); -- South Korea
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 23); -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 28); -- Melancholic

-- 파일럿 (Movie_ID = 4)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (4, 4);  -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (4, 20); -- South Korea
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (4, 25); -- Suspenseful

-- 트위스터스 (Movie_ID = 5)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (5, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (5, 16); -- USA
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (5, 30); -- Violent

-- 헤드리거 (Movie_ID = 6)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (6, 5);  -- Horror
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (6, 16); -- USA
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (6, 23); -- Dark

-- 베놈: 라스트 댄스 (Movie_ID = 7)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (7, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (7, 9);  -- Marvel Studios
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (7, 16); -- USA
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (7, 30); -- Violent

-- 위키드 (Movie_ID = 8)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (8, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (8, 12); -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (8, 16); -- USA
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (8, 26); -- Romantic

-- 글래디에이터 2 (Movie_ID = 9)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (9, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (9, 13); -- Paramount
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (9, 19); -- UK
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (9, 23); -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (9, 30); -- Violent

-- 모아나 2 (Movie_ID = 10)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (10, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (10, 12); -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (10, 16); -- USA
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (10, 27); -- Inspiring

SELECT column_name, data_type
FROM user_tab_columns
WHERE table_name = 'TAGS';

select * from TAGS;

SELECT * FROM MOVIES;