CREATE TABLE TAGS(
                     TAG_ID NUMBER(3) PRIMARY KEY,
                     TAG_NAME varchar2 (40) UNIQUE NOT NULL,
                     TAG_TYPE varchar2 (10) NOT NULL
);

CREATE SEQUENCE SEQ_TAGS START WITH 1 INCREMENT BY 1 MAXVALUE 999;

-- Genre (장르) 8개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Action', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Comedy', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Drama', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Thriller', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Horror', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Romance', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Fantasy', 'Genre');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Sci-Fi', 'Genre');

-- Studio (제작사) 7개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Marvel Studios', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Pixar', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Warner Bros.', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Disney', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Paramount', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Universal', 'Studio');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Studio Ghibli', 'Studio');

-- Country (국가) 7개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'USA', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Japan', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'France', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'UK', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'South Korea', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'India', 'Country');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Germany', 'Country');

-- Mood (분위기) 8개
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Dark', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Lighthearted', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Suspenseful', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Romantic', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Inspiring', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Melancholic', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Uplifting', 'Mood');
INSERT INTO TAGS (TAG_ID, TAG_NAME, TAG_TYPE) VALUES (SEQ_TAGS.NEXTVAL, 'Violent', 'Mood');

-- ===========================================================================
-- ===========================================================================
-- =========================MOVIE_TAGS TABLE================================
-- ===========================================================================
-- ===========================================================================

CREATE TABLE MOVIE_TAGS (
                            MOVIE_ID NUMBER(3),
                            TAG_ID NUMBER(3) ,
                            PRIMARY KEY (MOVIE_ID, TAG_ID),
                            FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID) ON DELETE CASCADE,
                            FOREIGN KEY (TAG_ID) REFERENCES TAGS(TAG_ID) ON DELETE CASCADE
);


SELECT column_name, data_type
FROM user_tab_columns
WHERE table_name = 'TAGS';

select * from MOVIE_TAGS;

-- A Quiet Place: Day One (Horror, Dark, Suspenseful, Paramount, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (77, 5);   -- Horror
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (77, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (77, 25);  -- Suspenseful
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (77, 13);  -- Paramount
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (77, 16);  -- USA

-- Avatar 3 (Sci-Fi, Action, Fantasy, Disney, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (122, 8);  -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (122, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (122, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (122, 12); -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (122, 16); -- USA

-- Avengers: Secret Wars (Action, Sci-Fi, Marvel Studios, Violent, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (120, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (120, 8);  -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (120, 9);  -- Marvel Studios
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (120, 30); -- Violent
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (120, 16); -- USA

-- Beetlejuice Beetlejuice (Comedy, Dark, Fantasy, Warner Bros., USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (99, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (99, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (99, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (99, 11);  -- Warner Bros.
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (99, 16);  -- USA

-- Borderlands (Sci-Fi, Action, Violent, Dark, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (98, 8);   -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (98, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (98, 30);  -- Violent
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (98, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (98, 16);  -- USA



-- Challengers (Drama, Romance, Melancholic, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (85, 3);   -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (85, 6);   -- Romance
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (85, 28);  -- Melancholic
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (85, 16);  -- USA

-- Civil War (Action, Thriller, War, Dark, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (87, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (87, 4);   -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (87, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (87, 16);  -- USA

-- Deadpool & Wolverine (Action, Comedy, Marvel Studios, Violent, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (70, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (70, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (70, 9);   -- Marvel Studios
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (70, 30);  -- Violent
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (70, 16);  -- USA

-- Despicable Me 4 (Comedy, Disney, Lighthearted, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 2);    -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 12);   -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 24);   -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (2, 16);   -- USA

-- Dream (Drama, Inspiring, South Korea)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (6, 3);    -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (6, 27);   -- Inspiring
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (6, 20);   -- South Korea


-- Dune: Part Two (Sci-Fi, Action, Dark, Violent, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (88, 8);   -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (88, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (88, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (88, 30);  -- Violent
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (88, 16);  -- USA

-- Elio (Fantasy, Pixar, Lighthearted, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (91, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (91, 10);  -- Pixar
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (91, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (91, 16);  -- USA

-- Escape (Thriller, Suspenseful, Drama, Germany)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 4);    -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 25);   -- Suspenseful
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 3);    -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (3, 22);   -- Germany

-- Fantastic Four (Action, Sci-Fi, Marvel Studios, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (123, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (123, 8);  -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (123, 9);  -- Marvel Studios
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (123, 16); -- USA

-- Frozen 3 (Fantasy, Disney, Musical 느낌으로 Lighthearted, Uplifting)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (129, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (129, 12); -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (129, 24); -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (129, 29); -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (129, 16); -- USA


-- Ghostbusters: Frozen Empire (Comedy, Fantasy, Dark, Action, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (86, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (86, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (86, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (86, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (86, 16);  -- USA

-- Gladiator 2 (Action, Drama, Violent, Melancholic, UK)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (115, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (115, 3);  -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (115, 30); -- Violent
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (115, 28); -- Melancholic
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (115, 19); -- UK

-- How to Train Your Dragon (Live-Action) (Fantasy, Action, Uplifting, Universal, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (126, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (126, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (126, 29); -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (126, 14); -- Universal
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (126, 16); -- USA

-- IF (Fantasy, Lighthearted, Comedy, Inspiring, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (73, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (73, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (73, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (73, 27);  -- Inspiring
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (73, 16);  -- USA

-- Inside Out 2 (Pixar, Fantasy, Lighthearted, Uplifting, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 10);   -- Pixar
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 7);    -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 24);   -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 29);   -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (1, 16);   -- USA


-- Inside the Yellow Cocoon Shell (Drama, Melancholic, France, Japan)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (83, 3);   -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (83, 28);  -- Melancholic
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (83, 18);  -- France
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (83, 17);  -- Japan

-- Kingdom of the Planet of the Apes (Action, Sci-Fi, Thriller, Dark, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (84, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (84, 8);   -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (84, 4);   -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (84, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (84, 16);  -- USA

-- Kung Fu Panda 4 (Comedy, Action, Lighthearted, Uplifting, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (71, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (71, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (71, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (71, 29);  -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (71, 16);  -- USA

-- Migration (Comedy, Disney, Lighthearted, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (82, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (82, 12);  -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (82, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (82, 16);  -- USA

-- Minecraft: The Movie (Fantasy, Adventure 느낌의 Action, Inspiring, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (127, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (127, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (127, 27);  -- Inspiring
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (127, 16);  -- USA


-- Moana 2 (Disney, Fantasy, Adventure 느낌의 Inspiring, Lighthearted, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (78, 12);  -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (78, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (78, 27);  -- Inspiring
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (78, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (78, 16);  -- USA

-- Mufasa: The Lion King (Disney, Drama, Uplifting, Melancholic, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (79, 12);  -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (79, 3);   -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (79, 29);  -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (79, 28);  -- Melancholic
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (79, 16);  -- USA

-- Paddington in Peru (Comedy, Lighthearted, UK, Family 느낌)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (113, 2);  -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (113, 24); -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (113, 19); -- UK

-- Pilot (Suspenseful, Thriller, Germany, Dark)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (4, 25);   -- Suspenseful
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (4, 4);    -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (4, 22);   -- Germany
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (4, 23);   -- Dark

-- Robot Dreams (Drama, Japan, Melancholic, Inspiring)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (90, 3);   -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (90, 17);  -- Japan
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (90, 28);  -- Melancholic
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (90, 27);  -- Inspiring



-- Shrek 5 (Comedy, Fantasy, Lighthearted, Uplifting, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (119, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (119, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (119, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (119, 29);  -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (119, 16);  -- USA

-- Speak (Drama, Melancholic, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (101, 3);   -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (101, 28);  -- Melancholic
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (101, 16);  -- USA

-- Speak No Evil (Thriller, Horror, Suspenseful, Dark, Germany)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (92, 4);    -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (92, 5);    -- Horror
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (92, 25);   -- Suspenseful
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (92, 23);   -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (92, 22);   -- Germany

-- Superman: Legacy (Action, Sci-Fi, Uplifting, Warner Bros., USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (144, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (144, 8);   -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (144, 29);  -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (144, 11);  -- Warner Bros.
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (144, 16);  -- USA

-- Tangled: Ever After (Disney, Romance, Fantasy, Lighthearted, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (131, 12);  -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (131, 6);   -- Romance
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (131, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (131, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (131, 16);  -- USA


-- The Boy and the Heron (Fantasy, Drama, Studio Ghibli, Japan, Melancholic)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (80, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (80, 3);   -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (80, 15);  -- Studio Ghibli
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (80, 17);  -- Japan
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (80, 28);  -- Melancholic

-- The Fall Guy (Action, Comedy, Romance, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (72, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (72, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (72, 6);   -- Romance
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (72, 16);  -- USA

-- The Garfield Movie (Comedy, Lighthearted, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (95, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (95, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (95, 16);  -- USA

-- The Lord of the Rings: The War of the Rohirrim (Fantasy, Action, Dark, Violent, UK)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (124, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (124, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (124, 23); -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (124, 30); -- Violent
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (124, 19); -- UK

-- The Smurfs Musical (Fantasy, Comedy, Musical 느낌의 Lighthearted, Uplifting, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (128, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (128, 2);  -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (128, 24); -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (128, 29); -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (128, 16); -- USA


-- The Super Mario Bros. Movie 2 (Fantasy, Comedy, Lighthearted, Universal, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (121, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (121, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (121, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (121, 14);  -- Universal
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (121, 16);  -- USA

-- The Watchers (Horror, Thriller, Suspenseful, Dark, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (97, 5);    -- Horror
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (97, 4);    -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (97, 25);   -- Suspenseful
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (97, 23);   -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (97, 16);   -- USA

-- The Wild Robot (Drama, Inspiring, Uplifting, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (143, 3);   -- Drama
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (143, 27);  -- Inspiring
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (143, 29);  -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (143, 16);  -- USA

-- Trap (Thriller, Suspenseful, Dark, Germany)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (100, 4);   -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (100, 25);  -- Suspenseful
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (100, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (100, 22);  -- Germany

-- Tron: Ares (Sci-Fi, Action, Dark, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (125, 8);   -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (125, 1);   -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (125, 23);  -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (125, 16);  -- USA


-- Twisters (Action, Thriller, Suspenseful, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (5, 1);    -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (5, 4);    -- Thriller
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (5, 25);   -- Suspenseful
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (5, 16);   -- USA

-- Venom: The Last Dance (Action, Sci-Fi, Marvel Studios, Dark, Violent)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (142, 1);  -- Action
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (142, 8);  -- Sci-Fi
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (142, 9);  -- Marvel Studios
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (142, 23); -- Dark
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (142, 30); -- Violent

-- Wicked: Part One (Fantasy, Romance, Musical 느낌의 Uplifting, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (117, 7);  -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (117, 6);  -- Romance
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (117, 29); -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (117, 16); -- USA

-- Wish (Disney, Fantasy, Lighthearted, Inspiring, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (81, 12);  -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (81, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (81, 24);  -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (81, 27);  -- Inspiring
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (81, 16);  -- USA

-- Wish Dragon 2 (Fantasy, Comedy, Inspiring, China 느낌으로 중국 태그는 생략)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (89, 7);   -- Fantasy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (89, 2);   -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (89, 27);  -- Inspiring

-- Zootopia 2 (Disney, Comedy, Lighthearted, Uplifting, USA)
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (130, 12); -- Disney
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (130, 2);  -- Comedy
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (130, 24); -- Lighthearted
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (130, 29); -- Uplifting
INSERT INTO MOVIE_TAGS (MOVIE_ID, TAG_ID) VALUES (130, 16); -- USA


SELECT MOVIE_ID,TITLE FROM MOVIES;

select TAG_ID,TAG_NAME from TAGS;

