-- ========================================
-- 4. 영화 테이블 (MOVIES)
-- ========================================

DROP TABLE MOVIES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MOVIE_ID;

-- 테이블 생성
CREATE TABLE MOVIES (
                        MOVIE_ID NUMBER(3) PRIMARY KEY,
                        TITLE VARCHAR2(100) NOT NULL,
                        DIRECTOR VARCHAR2(100) NOT NULL,
                        ACTOR VARCHAR2(200) NOT NULL,
                        GENRE VARCHAR2(50) NOT NULL,
                        RATING VARCHAR2(20) NOT NULL,
                        USER_CRITIC NUMBER(2,1) DEFAULT 0 CHECK (USER_CRITIC >= 0 AND USER_CRITIC <= 5),
                        PRO_CRITIC NUMBER(2,1) DEFAULT 0 CHECK (PRO_CRITIC >= 0 AND PRO_CRITIC <= 5),
                        DESCRIPTION VARCHAR2(1000),
                        RUNNING_TIME NUMBER(3) NOT NULL,
                        POSTER_URL VARCHAR2(500)
);
ALTER TABLE MOVIES
    ADD RELEASE_DATE DATE;

ALTER TABLE MOVIES
    ADD CONSTRAINT UQ_MOVIES_TITLE UNIQUE (TITLE);

select * from MOVIES;
--별점으로 만든 랭킹
SELECT TITLE,USER_CRITIC,ROW_NUMBER() OVER (ORDER BY USER_CRITIC DESC) AS RANKING
FROM MOVIES;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MOVIE_ID START WITH 1 INCREMENT BY 1 MAXVALUE 999;


-- 커밋
COMMIT;

-- 확인 쿼리
SELECT * FROM MOVIES ORDER BY MOVIE_ID;

-- 장르별 영화 수 확인
SELECT GENRE, COUNT(*) as MOVIE_COUNT
FROM MOVIES
GROUP BY GENRE
ORDER BY MOVIE_COUNT DESC;