-- ========================================
-- 5. 상영시간 테이블 (RUNTIMES)
-- ========================================

-- 테이블 생성
CREATE TABLE RUNTIMES (
                          RUNTIME_ID NUMBER(4) PRIMARY KEY,        -- 상영시간은 많을 수 있으므로 4자리
                          MOVIE_ID NUMBER(3) NOT NULL,
                          ROOM_ID NUMBER(2) NOT NULL,
                          RUN_DATE DATE NOT NULL,
                          START_TIME VARCHAR2(5) NOT NULL,
                          PRICE NUMBER(6) DEFAULT 12000 NOT NULL,  -- 가격은 6자리 (999,999원까지)
                          AVAILABLE_SEATS NUMBER(3) NOT NULL,
                          CONSTRAINT FK_RUNTIMES_MOVIE FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
                          CONSTRAINT FK_RUNTIMES_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_RUNTIME_ID START WITH 1 INCREMENT BY 1 MAXVALUE 9999;

-- 오늘 상영시간 데이터
-- 인사이드 아웃 2
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (1, 1, 1, CURRENT_DATE, '10:00', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (2, 1, 1, CURRENT_DATE, '14:30', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (3, 1, 2, CURRENT_DATE, '12:30', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (4, 1, 3, CURRENT_DATE, '17:30', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (5, 1, 1, CURRENT_DATE, '22:30', 12000, 0); -- 매진

-- 디스피커블 미 4
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (6, 2, 1, CURRENT_DATE, '19:00', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (7, 2, 2, CURRENT_DATE, '11:00', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (8, 2, 3, CURRENT_DATE, '09:30', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (9, 2, 2, CURRENT_DATE, '16:45', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (10, 2, 4, CURRENT_DATE, '21:45', 14000, 50);

-- 탈주
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (11, 3, 2, CURRENT_DATE, '16:00', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (12, 3, 1, CURRENT_DATE, '13:40', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (13, 3, 3, CURRENT_DATE, '19:00', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (14, 3, 2, CURRENT_DATE, '21:40', 12000, 80);

-- 헤드리거
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (15, 4, 1, CURRENT_DATE, '10:30', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (16, 4, 2, CURRENT_DATE, '15:50', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (17, 4, 4, CURRENT_DATE, '21:10', 14000, 50);

-- 파일럿
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (18, 5, 2, CURRENT_DATE, '11:20', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (19, 5, 3, CURRENT_DATE, '16:40', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (20, 5, 1, CURRENT_DATE, '22:00', 12000, 60);

-- 트위스터스
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (21, 6, 3, CURRENT_DATE, '09:45', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (22, 6, 1, CURRENT_DATE, '15:05', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (23, 6, 4, CURRENT_DATE, '20:25', 14000, 50);

-- 내일 상영시간 데이터
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (24, 1, 1, CURRENT_DATE + 1, '10:00', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (25, 1, 2, CURRENT_DATE + 1, '14:30', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (26, 1, 3, CURRENT_DATE + 1, '19:00', 15000, 100);

INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (27, 2, 2, CURRENT_DATE + 1, '11:00', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (28, 2, 1, CURRENT_DATE + 1, '16:00', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (29, 2, 4, CURRENT_DATE + 1, '21:30', 14000, 50);

INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (30, 3, 3, CURRENT_DATE + 1, '12:00', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (31, 3, 2, CURRENT_DATE + 1, '18:00', 12000, 80);

-- 모레부터 6일 후까지의 상영시간 (간략하게)
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (32, 1, 1, CURRENT_DATE + 2, '10:30', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (33, 2, 2, CURRENT_DATE + 2, '14:15', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (34, 3, 3, CURRENT_DATE + 2, '18:45', 15000, 100);

INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (35, 1, 2, CURRENT_DATE + 3, '11:00', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (36, 4, 1, CURRENT_DATE + 3, '15:20', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (37, 5, 4, CURRENT_DATE + 3, '19:40', 14000, 50);

INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (38, 2, 3, CURRENT_DATE + 4, '10:15', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (39, 6, 1, CURRENT_DATE + 4, '16:30', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (40, 3, 2, CURRENT_DATE + 4, '20:00', 12000, 80);

-- 주말 (5일 후, 6일 후) - 더 많은 상영시간
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (41, 1, 1, CURRENT_DATE + 5, '09:30', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (42, 1, 2, CURRENT_DATE + 5, '13:00', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (43, 1, 3, CURRENT_DATE + 5, '16:30', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (44, 1, 4, CURRENT_DATE + 5, '20:00', 14000, 50);

INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (45, 2, 1, CURRENT_DATE + 6, '10:00', 12000, 60);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (46, 2, 2, CURRENT_DATE + 6, '14:30', 12000, 80);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (47, 3, 3, CURRENT_DATE + 6, '18:00', 15000, 100);
INSERT INTO RUNTIMES (RUNTIME_ID, MOVIE_ID, ROOM_ID, RUN_DATE, START_TIME, PRICE, AVAILABLE_SEATS)
VALUES (48, 4, 4, CURRENT_DATE + 6, '21:30', 14000, 50);

-- 커밋
COMMIT;

-- 확인 쿼리
-- 날짜별 상영 건수
SELECT RUN_DATE, COUNT(*) as SHOWTIME_COUNT
FROM RUNTIMES
GROUP BY RUN_DATE
ORDER BY RUN_DATE;

-- 영화별 상영 건수
SELECT m.TITLE, COUNT(r.RUNTIME_ID) as SHOWTIME_COUNT
FROM MOVIES m
         LEFT JOIN RUNTIMES r ON m.MOVIE_ID = r.MOVIE_ID
GROUP BY m.MOVIE_ID, m.TITLE
ORDER BY SHOWTIME_COUNT DESC;

-- 상영관별 이용률
SELECT rm.ROOM_NAME,
       COUNT(r.RUNTIME_ID)              as SHOWTIME_COUNT,
       ROUND(AVG(r.AVAILABLE_SEATS), 2) as AVG_AVAILABLE_SEATS
FROM ROOMS rm
         LEFT JOIN RUNTIMES r ON rm.ROOM_ID = r.ROOM_ID
GROUP BY rm.ROOM_ID, rm.ROOM_NAME
ORDER BY SHOWTIME_COUNT DESC;

SELECT * FROM runtimes WHERE room_id = 1 AND run_date = '2025-07-09';
select * from RUNTIMES;