-- ========================================
-- RESERVATIONS 테이블 수정
-- U_ID를 VARCHAR2(20)으로 변경하고 기존 데이터 마이그레이션
-- ========================================

-- 1. 기존 테이블 백업 (안전을 위해)
CREATE TABLE RESERVATIONS_BACKUP AS SELECT * FROM RESERVATIONS;

-- 2. 기존 테이블 삭제
DROP TABLE RESERVATIONS CASCADE CONSTRAINTS;

-- 3. 새로운 RESERVATIONS 테이블 생성 (U_ID를 VARCHAR2로 변경)
CREATE TABLE RESERVATIONS (
                              RESERVATION_ID NUMBER PRIMARY KEY,
                              U_ID VARCHAR2(20) NOT NULL,  -- INTEGER에서 VARCHAR2(20)로 변경
                              RUNTIME_ID NUMBER NOT NULL,
                              ADULT NUMBER DEFAULT 0,
                              YOUTH NUMBER DEFAULT 0,
                              CHILD NUMBER DEFAULT 0,
                              TOTAL_AMOUNT NUMBER NOT NULL,
                              RESERVATION_STATUS VARCHAR2(20) DEFAULT '예약완료',
                              RESERVED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- 외래 키 제약조건
                              CONSTRAINT FK_RESERVATIONS_USER FOREIGN KEY (U_ID) REFERENCES USERS(U_ID),
                              CONSTRAINT FK_RESERVATIONS_RUNTIME FOREIGN KEY (RUNTIME_ID) REFERENCES RUNTIMES(RUNTIME_ID)
);

-- 4. 시퀀스 재생성 (기존 것이 있다면 삭제 후 생성)
DROP SEQUENCE SEQ_RESERVATION_ID;
CREATE SEQUENCE SEQ_RESERVATION_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- 5. 사용자 ID 매핑 테이블 (기존 정수 ID를 문자열 ID로 매핑)
-- 1 -> kim123 (기본 테스트 사용자)
-- 2 -> lee456
-- 3 -> park789
-- 4 -> choi101
-- 5 -> jung202

-- 6. 새로운 예약 데이터 삽입 (기존 CSV 데이터를 여러 사용자에게 분산)
INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'kim123', 67, 2, 0, 0, 24000, '예약완료', TO_TIMESTAMP('2025-07-10 09:52:53.973061', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'kim123', 67, 1, 0, 0, 12000, '예약취소', TO_TIMESTAMP('2025-07-10 10:56:30.225832', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'lee456', 67, 2, 0, 0, 24000, '예약완료', TO_TIMESTAMP('2025-07-10 15:07:47.518481', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'park789', 49, 2, 0, 0, 24000, '예약취소', TO_TIMESTAMP('2025-07-09 23:10:11.336687', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'choi101', 49, 2, 0, 0, 24000, '예약완료', TO_TIMESTAMP('2025-07-09 23:13:09.433768', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'jung202', 49, 1, 1, 0, 15000, '예약완료', TO_TIMESTAMP('2025-07-09 23:14:20.123456', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'kim123', 70, 3, 0, 0, 36000, '예약완료', TO_TIMESTAMP('2025-07-10 16:30:45.789012', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'lee456', 52, 1, 2, 1, 22000, '예약완료', TO_TIMESTAMP('2025-07-10 11:15:30.456789', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'park789', 85, 2, 0, 0, 30000, '예약완료', TO_TIMESTAMP('2025-07-10 14:45:20.345678', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'choi101', 63, 1, 0, 0, 15000, '예약완료', TO_TIMESTAMP('2025-07-10 13:20:15.234567', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'jung202', 78, 2, 1, 0, 27000, '예약완료', TO_TIMESTAMP('2025-07-10 17:10:30.567890', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'kim123', 91, 1, 0, 0, 12000, '예약취소', TO_TIMESTAMP('2025-07-10 18:00:45.678901', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'lee456', 44, 4, 0, 0, 48000, '예약완료', TO_TIMESTAMP('2025-07-10 19:30:20.789012', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'park789', 58, 1, 1, 1, 19000, '예약완료', TO_TIMESTAMP('2025-07-10 20:15:35.890123', 'YYYY-MM-DD HH24:MI:SS.FF'));

INSERT INTO RESERVATIONS (RESERVATION_ID, U_ID, RUNTIME_ID, ADULT, YOUTH, CHILD, TOTAL_AMOUNT, RESERVATION_STATUS, RESERVED_AT) VALUES
    (SEQ_RESERVATION_ID.NEXTVAL, 'choi101', 75, 2, 0, 0, 24000, '예약완료', TO_TIMESTAMP('2025-07-10 21:45:10.901234', 'YYYY-MM-DD HH24:MI:SS.FF'));

-- 7. 인덱스 생성 (성능 최적화)
CREATE INDEX IDX_RESERVATIONS_USER ON RESERVATIONS(U_ID);
CREATE INDEX IDX_RESERVATIONS_RUNTIME ON RESERVATIONS(RUNTIME_ID);
CREATE INDEX IDX_RESERVATIONS_STATUS ON RESERVATIONS(RESERVATION_STATUS);
CREATE INDEX IDX_RESERVATIONS_DATE ON RESERVATIONS(RESERVED_AT);

-- 8. 데이터 확인
SELECT
    U_ID,
    COUNT(*) as 예약수,
    SUM(CASE WHEN RESERVATION_STATUS = '예약완료' THEN 1 ELSE 0 END) as 완료,
    SUM(CASE WHEN RESERVATION_STATUS = '예약취소' THEN 1 ELSE 0 END) as 취소,
    SUM(TOTAL_AMOUNT) as 총금액
FROM RESERVATIONS
GROUP BY U_ID
ORDER BY U_ID;

-- 9. 커밋
COMMIT;

-- 10. 확인 쿼리
SELECT
    r.RESERVATION_ID,
    r.U_ID,
    u.U_name,
    r.RUNTIME_ID,
    r.ADULT,
    r.YOUTH,
    r.CHILD,
    r.TOTAL_AMOUNT,
    r.RESERVATION_STATUS,
    r.RESERVED_AT
FROM RESERVATIONS r
         JOIN USERS u ON r.U_ID = u.U_ID
ORDER BY r.RESERVED_AT DESC;

PROMPT 'RESERVATIONS 테이블 수정 및 데이터 마이그레이션 완료!';