-- ========================================
-- RESERVATION_SEATS 테이블 생성 및 데이터 삽입
-- 새로운 RESERVATIONS 데이터에 맞춰 좌석 정보 추가
-- ========================================

-- 1. 기존 테이블 삭제 (있다면)
DROP TABLE RESERVATION_SEATS CASCADE CONSTRAINTS;

-- 2. RESERVATION_SEATS 테이블 생성
CREATE TABLE RESERVATION_SEATS (
                                   RESERVATION_SEAT_ID NUMBER PRIMARY KEY,
                                   RESERVATION_ID NUMBER NOT NULL,
                                   SEAT_ID NUMBER NOT NULL,

    -- 외래 키 제약조건
                                   CONSTRAINT FK_RESERVATION_SEATS_RESERVATION FOREIGN KEY (RESERVATION_ID) REFERENCES RESERVATIONS(RESERVATION_ID),
                                   CONSTRAINT FK_RESERVATION_SEATS_SEAT FOREIGN KEY (SEAT_ID) REFERENCES SEATS(SEAT_ID),

    -- 같은 예약에서 같은 좌석 중복 방지
                                   CONSTRAINT UK_RESERVATION_SEATS UNIQUE (RESERVATION_ID, SEAT_ID)
);

-- 3. 시퀀스 생성
DROP SEQUENCE SEQ_RESERVATION_SEAT_ID;
CREATE SEQUENCE SEQ_RESERVATION_SEAT_ID START WITH 1 INCREMENT BY 1 NOCACHE;

-- 4. 새로운 예약 좌석 데이터 삽입
-- 예약 ID에 맞춰 좌석 정보 추가 (실제 예약 테이블의 RESERVATION_ID와 매핑)

-- 첫 번째 예약 (kim123, 2명) - 좌석 A1, A2
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 1, 1);  -- A1
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 1, 2);  -- A2

-- 두 번째 예약 (kim123, 1명, 취소됨) - 좌석 B3
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 2, 13);  -- B3

-- 세 번째 예약 (lee456, 2명) - 좌석 C4, C5
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 3, 24);  -- C4
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 3, 25);  -- C5

-- 네 번째 예약 (park789, 2명, 취소됨) - 좌석 D6, D7
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 4, 36);  -- D6
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 4, 37);  -- D7

-- 다섯 번째 예약 (choi101, 2명) - 좌석 E8, E9
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 5, 48);  -- E8
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 5, 49);  -- E9

-- 여섯 번째 예약 (jung202, 1명 + 1명 청소년) - 좌석 F10, F11
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 6, 60);  -- F10
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 6, 61);  -- F11

-- 일곱 번째 예약 (kim123, 3명) - 좌석 A5, A6, A7
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 7, 5);   -- A5
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 7, 6);   -- A6
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 7, 7);   -- A7

-- 여덟 번째 예약 (lee456, 1명 + 2명 청소년 + 1명 어린이) - 좌석 B1, B2, B3, B4
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 8, 11);  -- B1
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 8, 12);  -- B2
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 8, 13);  -- B3
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 8, 14);  -- B4

-- 아홉 번째 예약 (park789, 2명) - 좌석 C1, C2
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 9, 21);  -- C1
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 9, 22);  -- C2

-- 열 번째 예약 (choi101, 1명) - 좌석 D1
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 10, 31);  -- D1

-- 열한 번째 예약 (jung202, 2명 + 1명 청소년) - 좌석 E1, E2, E3
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 11, 41);  -- E1
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 11, 42);  -- E2
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 11, 43);  -- E3

-- 열두 번째 예약 (kim123, 1명, 취소됨) - 좌석 F1
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 12, 51);  -- F1

-- 열세 번째 예약 (lee456, 4명) - 좌석 A8, A9, A10, B5
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 13, 8);   -- A8
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 13, 9);   -- A9
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 13, 10);  -- A10
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 13, 15);  -- B5

-- 열네 번째 예약 (park789, 1명 + 1명 청소년 + 1명 어린이) - 좌석 C6, C7, C8
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 14, 26);  -- C6
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 14, 27);  -- C7
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 14, 28);  -- C8

-- 열다섯 번째 예약 (choi101, 2명) - 좌석 D2, D3
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 15, 32);  -- D2
INSERT INTO RESERVATION_SEATS (RESERVATION_SEAT_ID, RESERVATION_ID, SEAT_ID)
VALUES (SEQ_RESERVATION_SEAT_ID.NEXTVAL, 15, 33);  -- D3

-- 5. 인덱스 생성 (성능 최적화)
CREATE INDEX IDX_RESERVATION_SEATS_RESERVATION ON RESERVATION_SEATS(RESERVATION_ID);
CREATE INDEX IDX_RESERVATION_SEATS_SEAT ON RESERVATION_SEATS(SEAT_ID);

-- 6. 데이터 확인
SELECT
    rs.RESERVATION_ID,
    COUNT(rs.SEAT_ID) as 좌석수,
    LISTAGG(s.SEAT_ROW || s.SEAT_NUMBER, ', ') WITHIN GROUP (ORDER BY s.SEAT_ROW, s.SEAT_NUMBER) as 좌석목록
FROM RESERVATION_SEATS rs
         JOIN SEATS s ON rs.SEAT_ID = s.SEAT_ID
GROUP BY rs.RESERVATION_ID
ORDER BY rs.RESERVATION_ID;

-- 7. 예약별 상세 정보 확인
SELECT
    r.RESERVATION_ID,
    r.U_ID,
    r.ADULT + r.YOUTH + r.CHILD as 총인원,
    COUNT(rs.SEAT_ID) as 좌석수,
    LISTAGG(s.SEAT_ROW || s.SEAT_NUMBER, ', ') WITHIN GROUP (ORDER BY s.SEAT_ROW, s.SEAT_NUMBER) as 좌석목록,
    r.RESERVATION_STATUS
FROM RESERVATIONS r
         LEFT JOIN RESERVATION_SEATS rs ON r.RESERVATION_ID = rs.RESERVATION_ID
         LEFT JOIN SEATS s ON rs.SEAT_ID = s.SEAT_ID
GROUP BY r.RESERVATION_ID, r.U_ID, r.ADULT, r.YOUTH, r.CHILD, r.RESERVATION_STATUS
ORDER BY r.RESERVATION_ID;

-- 8. 커밋
COMMIT;

PROMPT 'RESERVATION_SEATS 테이블 생성 및 데이터 삽입 완료!';