CREATE TABLE reviews (
                         r_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         movie_id NUMBER NOT NULL,
                         u_id VARCHAR2(50) NOT NULL,
                         r_rating NUMBER(1) CHECK (r_rating BETWEEN 1 AND 5),
                         r_text VARCHAR2(999) NOT NULL,
                         r_date DATE DEFAULT SYSDATE,

                         CONSTRAINT fk_reviews_movie
                             FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
                                 ON DELETE CASCADE,

                         CONSTRAINT fk_reviews_user
                             FOREIGN KEY (u_id) REFERENCES users(u_id)
                                 ON DELETE CASCADE
);



SELECT
    movie_id,
    ROUND(AVG(r_rating), 1) AS avg_rating
FROM
    reviews
WHERE
    movie_id = 115
GROUP BY
    movie_id;



